package monitor

import "strings"

func (monitorTask *MonitorTask) findSubjectCode ()(bool, string) {
	for subjectCode, subject := range subjects {
        if strings.ToLower(subject) == strings.ToLower(monitorTask.Subject){
			return true, subjectCode
		}
    }
	return false, ""
}

var subjects = map[string]string{
	"ACCT": "Accounting",
	"AMST": "American Studies",
	"ANTH": "Anthropology",
	"ARAB": "Arabic",
	"ARTH": "Art History",
	"BLST": "Bachelor of Liberal Studies",
	"BIOL": "Biology",
	"BUAD": "Business Administration",
	"BLAW": "Business Law",
	"CHEM": "Chemistry",
	"CHIN": "Chinese",
	"CLAS": "Classics",
	"CPRD": "Classics, Phil &amp; Religion",
	"COMM": "Communication",
	"CPSC": "Computer Science",
	"EDCI": "Curriculum &amp; Instruction",
	"CYBR": "Cybersecurity",
	"DANC": "Dance",
	"DATA": "Data Science",
	"DSCI": "Decision Sciences",
	"DGST": "Digital Studies",
	"ECON": "Economics",
	"EDUC": "Education",
	"ENGL": "English",
	"EESC": "Environmental Earth Science",
	"FINC": "Finance",
	"FSEM": "First-Year Seminar",
	"FREN": "French",
	"GISC": "Geographic Info Sciences",
	"MSGA": "Geographic Info Sciences",
	"GEOG": "Geography",
	"GERM": "German",
	"GBUS": "Grad Business Administration",
	"GREK": "Greek",
	"HEED": "Health Education",
	"HSCI": "Health Science",
	"HISP": "Historic Preservation",
	"HIST": "History",
	"HONR": "Honors",
	"INDT": "Instructional Design and Tech",
	"IDIS": "Interdisciplinary Studies",
	"ITAL": "Italian",
	"JAPN": "Japanese",
	"JOUR": "Journalism",
	"LATN": "Latin",
	"LRSP": "Leadership",
	"LING": "Linguistics",
	"MGMT": "Management",
	"MIST": "Management Information Systems",
	"MKTG": "Marketing",
	"MATH": "Mathematics",
	"MSCI": "Military Science",
	"MUSC": "Music",
	"MUHL": "Music History and Literature",
	"MUPR": "Music Performance",
	"MUTC": "Music Technology",
	"MUTH": "Music Theory",
	"NURS": "Nursing",
	"PHIL": "Philosophy",
	"PHYD": "Physical Education",
	"PHYS": "Physics",
	"PSCI": "Political Science",
	"PSYC": "Psychology",
	"RELG": "Religion",
	"SOCG": "Sociology",
	"SPAN": "Spanish",
	"EDSE": "Special Education",
	"STAT": "Statistics",
	"ARTS": "Studio Art",
	"TESL": "Teaching Eng as a Sec Lang",
	"THEA": "Theatre",
	"URES": "Undergraduate Research",
	"WGST": "Women and Gender Studies",
}